name: Execucao de testes
run-name: Running - ExecuÃ§Ã£o de testes

on:
  push:
    branches: 
      - feat-pipeline-conexao
  workflow_dispatch:
 
jobs:
  generate-and-test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Clone do repositÃ³rio
        run: |
          git clone https://github.com/Felipe-Janazi/integration-agent.git

      - name: Entrando no repositÃ³rio
        run: |
          cd integration-agent
          git checkout feat-pipeline-conexao

          
      - name: InstalaÃ§Ã£o de dependÃªncias
        run: |
          npm init -y
          npm i -D @playwright/test typescript ts-node

      - name: ExecuÃ§Ã£o de testes
        run: |
            npx playwright install
            npx playwright test
        continue-on-error: true


  Analise-de-resposta:
    runs-on: ubuntu-latest
    needs: generate-and-test
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
 
      - name: Install dependencies
        run: |
          pip install groq pytest pytest-bdd
 
      - name: Generate analises
        run: python ai/generate_analise.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Commit analises
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if ls ai/analysis/*.txt 1> /dev/null 2>&1; then
            git add ai/analysis/*.txt
            git commit -m "ğŸ¤– Gerando analises e conselhos automÃ¡ticos [skip ci]" || echo "Nada para commitar"
            git push
          else
            echo "Nenhuma anÃ¡lise gerada, nada para commitar"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
