name: Valida√ß√£o de testes
run-name: Running - Valida√ß√£o de testes

on:
  workflow_run:
    workflows: [Execu√ß√£o de testes]
    types: [completed]

jobs:
  generate-and-test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
 
      - name: Install dependencies
        run: |
          pip install groq pytest pytest-bdd
 
      - name: Generate analises
        run: python ai/generate_analise.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Commit analises
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ai/bdd/*.feature ai/tests/*.py
          git commit -m "ü§ñ Gerando analises e conselhos autom√°ticos [skip ci]" || echo "Nada para commitar"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}